"""Implement systems and system_relations models

Revision ID: babeed7efd3a
Revises: 
Create Date: 2025-02-05 21:51:53.450201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'babeed7efd3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('description', sa.String(length=1024), nullable=False),
        sa.Column('codebase_id', sa.Integer(), nullable=True),
        sa.Column('database_id', sa.Integer(), nullable=True),
        sa.Column('service_url', sa.String(length=256), nullable=True, comment='URL with validation should be applied at application level'),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('system_summary', sa.Text(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sqlite_autoincrement=True
    )
    op.create_table('system_relations',
        sa.Column('parent_id', sa.Integer(), nullable=False),
        sa.Column('child_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['child_id'], ['systems.id']),
        sa.ForeignKeyConstraint(['parent_id'], ['systems.id']),
        sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_relations')
    op.drop_table('systems')
    # ### end Alembic commands ###
